name: neural-lam
channels:
  - pytorch
  - nvidia
  - pyg
dependencies:
  - Cartopy
  - dask
  - dask-jobqueue
  - imageio
  - ipython
  - matplotlib
  - netcdf4
  - networkx
  - numpy
  - pip
  - plotly
  - pyg
  - pyproj
  - pyprojroot
  - pytorch=2.2.2=py3.12_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8
  - pytorch-lightning
  - scikit-learn
  - scipy
  - shapely
  - torchaudio
  - torchvision
  - wandb
  - xarray
  - zarr
  - pip:
    - tueplots
    - codespell>=2.0.0
    - black>=21.9b0
    - isort>=5.9.3
    - flake8>=4.0.1
    - pylint>=3.0.3
    - pre-commit>=2.15.0
