name: danra
state:
  zarrs:
    - path: "data/danra/single_levels.zarr"
      dims:
        time: time
        level: null
        x: x
        y: y
        grid: null
      lat_lon_names:
        lon: lon
        lat: lat
    - path: "data/danra/height_levels.zarr"
      dims:
        time: time
        level: altitude
        x: x
        y: y
        grid: null
      lat_lon_names:
        lon: lon
        lat: lat
  surface_vars:
    - u10m
    - v10m
    - t2m
  surface_units:
    - m/s
    - m/s
    - K
  atmosphere_vars:
    - u
    - v
    - t
  atmosphere_units:
    - m/s
    - m/s
    - K
  levels:
    - 100
forcing:
  zarrs:
    - path: "data/danra/single_levels.zarr"
      dims:
        time: time
        level: null
        x: x
        y: y
        grid: null
      lat_lon_names:
        lon: lon
        lat: lat
    - path: "data/forcings.zarr"
      dims:
        time: time
        level: null
        x: x
        y: y
        grid: null
  surface_vars:
    - cape_column # just as a technical test
    - icei0m
    - vis0m
    - xhail0m
    - hour_cos
    - hour_sin
    - year_cos
    - year_sin
  surface_units:
    - J/kg
    - kg/m^2 # just as a technical test :)
    - m
    - m
    - ""
    - ""
    - ""
    - ""
  atmosphere_vars: null
  atmosphere_units: null
  levels: null
  window: 3 # Number of time steps to use for forcing (odd)
static:
  zarrs:
    - path: "data/danra/single_levels.zarr"
      dims:
        level: null
        x: x
        y: y
        grid: null
      lat_lon_names:
        lon: lon
        lat: lat
  surface_vars:
    - pres0m # just as a technical test
  surface_units:
    - Pa
  atmosphere_vars: null
  atmosphere_units: null
  levels: null
boundary:
  zarrs: # This is not used currently, but soon ERA% boundaries will be used
    - path: "gs://weatherbench2/datasets/era5/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr"
      dims:
        time: time
        level: level
        x: longitude
        y: latitude
        grid: null
      lat_lon_names:
        lon: longitude
        lat: latitude
  mask:
    path: "data/boundary_mask.zarr"
    dims:
      x: x
      y: y
  surface_vars:
    - t2m
  surface_units:
    - K
  atmosphere_vars: null
  atmosphere_units: null
  levels: null
  window: 3
utilities:
  normalization:
    zarrs:
      - path: "data/normalization.zarr"
        stats_vars:
          state_mean: state_mean
          state_std: state_std
          forcing_mean: forcing_mean
          forcing_std: forcing_std
          diff_mean: diff_mean
          diff_std: diff_std
    combined_stats:
      - vars:
        - icei0m
        - vis0m
      - vars:
        - cape_column
        - xhail0m
    non_normalized_vars:
      - hour_cos
      - hour_sin
      - year_cos
      - year_sin
grid_shape_state:
  y: 589
  x: 789
splits:
  train:
    start: 1990-09-01T00
    end: 1990-09-11T00
  val:
    start: 1990-09-11T03
    end: 1990-09-13T09
  test:
    start: 1990-09-11T03
    end: 1990-09-13T09
projection:
  class: LambertConformal # Name of class in cartopy.crs
  kwargs:
    central_longitude: 25
    central_latitude: 56.4
    standard_parallels: [50.4, 61.6]
  inverted: false # Whether the projection is inverted
