schema_version: v0.6.0
dataset_version: v0.1.0

output:
  variables:
    static: [grid_index, static_feature]
    state: [time, grid_index, state_feature]
    forcing: [time, grid_index, forcing_feature]
  coord_ranges:
    time:
      # COSMO sample interior: Janâ€“Feb 2016 with small buffer handled at download time
      start: 2016-01-01T00:00
      end: 2016-02-29T23:00
      step: PT1H
  chunking:
    time: 1
  splitting:
    dim: time
    splits:
      train:
        # Train on everything up to the last week of February
        start: 2016-01-01T00:00
        end: 2016-02-21T23:00
        compute_statistics:
          ops: [mean, std, diff_mean, diff_std]
          dims: [grid_index, time]
      val:
        # First half of the last week of February 2016
        start: 2016-02-22T00:00
        end: 2016-02-25T23:00
      test:
        # Second half of the last week of February 2016
        start: 2016-02-26T00:00
        end: 2016-02-29T23:00

inputs:
  cosmo_height_levels:
    path: cosmo_sample.zarr
    dims: [time, x, y, z]
    variables:
      U:
        z:
          values: [6, 12, 20, 27, 31, 39, 45, 60]
          units: "m/s"
      V:
        z:
          values: [6, 12, 20, 27, 31, 39, 45, 60]
          units: "m/s"
      PP:
        z:
          values: [6, 12, 20, 27, 31, 39, 45, 60]
          units: "Pa"
      T:
        z:
          values: [6, 12, 20, 27, 31, 39, 45, 60]
          units: "K"
      RELHUM:
        z:
          values: [6, 12, 20, 27, 31, 39, 45, 60]
          units: "%"
      W:
        z:
          values: [6, 12, 20, 27, 31, 39, 45, 60]
          units: "m/s"
    dim_mapping:
      time:
        method: rename
        dim: time
      state_feature:
        method: stack_variables_by_var_name
        dims: [z]
        name_format: "{var_name}_lev_{z}"
      grid_index:
        method: stack
        dims: [x, y]
    target_output_variable: state

  cosmo_surface:
    path: cosmo_sample.zarr
    dims: [time, x, y]
    variables:
      - T_2M
      - U_10M
      - V_10M
      - PMSL
      - PS
      - TOT_PREC
      - ASHFL_S
      - ASOB_S
      - ATHB_S
    dim_mapping:
      time:
        method: rename
        dim: time
      grid_index:
        method: stack
        dims: [x, y]
      state_feature:
        method: stack_variables_by_var_name
        name_format: "{var_name}"
    target_output_variable: state

  cosmo_forcing:
    path: cosmo_sample.zarr
    dims: [time, x, y]
    derived_variables:
      toa_radiation:
        kwargs:
          time: ds_input.time
          lat: ds_input.lat
          lon: ds_input.lon
        function: mllam_data_prep.ops.derive_variable.physical_field.calculate_toa_radiation
      hour_of_day_sin:
        kwargs:
          time: ds_input.time
          component: sin
        function: mllam_data_prep.ops.derive_variable.time_components.calculate_hour_of_day
      hour_of_day_cos:
        kwargs:
          time: ds_input.time
          component: cos
        function: mllam_data_prep.ops.derive_variable.time_components.calculate_hour_of_day
      day_of_year_sin:
        kwargs:
          time: ds_input.time
          component: sin
        function: mllam_data_prep.ops.derive_variable.time_components.calculate_day_of_year
      day_of_year_cos:
        kwargs:
          time: ds_input.time
          component: cos
        function: mllam_data_prep.ops.derive_variable.time_components.calculate_day_of_year
    dim_mapping:
      time:
        method: rename
        dim: time
      grid_index:
        method: stack
        dims: [x, y]
      forcing_feature:
        method: stack_variables_by_var_name
        name_format: "{var_name}"
    target_output_variable: forcing

  cosmo_orography:
    path: cosmo_sample.zarr
    dims: [x, y]
    variables:
      - HSURF
    dim_mapping:
      grid_index:
        method: stack
        dims: [x, y]
      static_feature:
        method: stack_variables_by_var_name
        name_format: "{var_name}"
    target_output_variable: static

  cosmo_land_sea_mask:
    path: cosmo_land_sea_mask.zarr
    dims: [x, y]
    variables:
      - lsm
    dim_mapping:
      grid_index:
        method: stack
        dims: [x, y]
      static_feature:
        method: stack_variables_by_var_name
        name_format: "{var_name}"
    target_output_variable: static


extra:
  projection:
    class_name: RotatedPole
    kwargs:
      central_rotated_longitude: 10
      pole_longitude: 190
      pole_latitude: 43
